version: "3.7"
services:
  client:
    container_name: webclient
    build: 
      context: ./
      dockerfile: Dockerfile
    ports:
      - "3006:80"
    restart: always
    env_file:
      - .env.local

